CREATE TABLE STUDENT(
ROLL_NO INT PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
CITY VARCHAR(20),
MARKS INT DEFAULT 0
);

INSERT INTO STUDENT
(ROLL_NO,NAME,CITY,MARKS)
VALUES
(110,"ADAM","DEDLHI",76),
(108,"BOB","MUMBAI",65),
(124,"CASEY","PUNE",94),
(112,"DUKE","PUNE",80);

SELECT* FROM STUDENT