SELECT* FROM STUDENT
WHERE MARKS>75;

SELECT DISTINCT CITY FROM STUDENT;
-- OR
SELECT CITY FROM STUDENT
GROUP BY CITY;

UPDATE STUDENT
SET CITY="DELHI"
WHERE CITY="DEDLHI" ;

-- FIND THE MAX MARKS OF STUDENTS FROM EACH CITY
SELECT CITY,MAX(MARKS) FROM STUDENT
GROUP BY CITY
ORDER BY MAX(MARKS) DESC;

SELECT AVG(MARKS) FROM STUDENT;

-- ADD A NEW COLUMN GRADE,ASSIGN A GRADE SUCH THAT
-- MARKS>80 GRADE=O
-- MARKS 70-80 GRADE=A
-- MARKS 60-70 GRADE=B
ALTER TABLE STUDENT
ADD COLUMN GRADE CHAR;

UPDATE STUDENT
SET GRADE="O"
WHERE MARKS>80;
 
UPDATE STUDENT
SET GRADE="A"
WHERE MARKS BETWEEN 70 AND 80;

UPDATE STUDENT
SET GRADE="B"
WHERE MARKS>=60 AND MARKS<=70;
SELECT * FROM STUDENT;


