-- WHERE clause 
USE college;

SELECT NAME,EMAIL,FOLLOWERS FROM USER
WHERE AGE+1>=16 OR FOLLOWERS>200;

SELECT NAME,EMAIL FROM USER
WHERE  AGE BETWEEN 15 AND 17;

SELECT NAME FROM USER
WHERE AGE+1>=15 AND NAME='BOB';

SELECT NAME,AGE 
FROM USER
WHERE EMAIL IN ('MARLEY@GMAIL.COM','BATMAN@GMAIL.COM','BOB@GMAIL.COM');

SELECT * FROM USER WHERE AGE NOT IN (18,20);

SELECT * FROM USER WHERE FOLLOWERS>=0 LIMIT 3;
SELECT * FROM USER WHERE FOLLOWERS>0 ORDER BY FOLLOWERS DESC LIMIT 3;
-- BY DEFAULT SORTING IS IN ASCENDING ORDER