-- GROUP BY CLAUSE

-- PRINTS THE NUMBER OF IDS AND AGE OF EACH AGE GROUP
SELECT COUNT(ID),AGE
FROM USER
GROUP BY AGE;

-- PRINTS MAXIMUM FOLLOWERS FROM EACH AGE GROUP
SELECT AGE,MAX(FOLLOWERS)
FROM USER
GROUP BY AGE;

-- WILL THROW ERROR BECAUSE IF SELECT ANYTHING OTHER THAN THE AGGREGATION FN 
-- WE WILL HAVE TO APPLY GROUP BY ON IT
SELECT AGE,MAX(FOLLOWERS)
FROM USER
GROUP BY AGE;