SELECT * FROM USER;

SET SQL_SAFE_UPDATES=0;

UPDATE USER
SET FOLLOWERS=600
WHERE AGE=16;
-- SAME FOR DELETE

ALTER TABLE USER
ADD COLUMN RANDOM2 INT;

ALTER TABLE USER
DROP COLUMN RANDOM2;

ALTER TABLE USER
RENAME TO USERS;   

ALTER TABLE USERS
CHANGE COLUMN followers supporters INT DEFAULT 0;

ALTER TABLE USER
MODIFY followers INT DEFAULT 5;
-- MODIFICATION WILL BE APPLIED FROM THE NEXT INSERTIONS

INSERT INTO USER
(ID,NAME,AGE,EMAIL)
VALUES
(10,'LUFFY',21,'LUFFY@GMAIL.COM');

-- EMPTIES THE TABLE
TRUNCATE TABLE USER;

-- DELETES THE TABLE ITSELF
DROP TABLE USER;

